language: generic
services:
  - docker

before_install:
  - docker build -t bappi2097/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bappi2097/react-test npm test

after_success:
  - docker build -t bappi2097/fibonacci-nginx ./nginx
  - docker build -t bappi2097/fibonacci-worker ./worker
  - docker build -t bappi2097/fibonacci-server ./server
  - docker build -t bappi2097/fibonacci-client ./client
